# Generated by Django 3.2.3 on 2021-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('outstanding', 'Outstanding'), ('no_status', 'No Status')], max_length=255, null=True),
        ),
    ]
