# Generated by Django 3.2.3 on 2021-06-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_auto_20210603_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
