# Generated by Django 3.2.3 on 2021-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_approvalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('outstanding', 'Outstanding'), ('no status', 'No Status'), ('pending', 'Pending')], max_length=255, null=True),
        ),
    ]
